name: Run Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-2204

    strategy:
      matrix:
        node-version: [12, 14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
